
 USE DBCamp
 go

 SET NOCOUNT ON
 INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES( '606-429-7977',NULL,'Ken','J','Sánchez','Ken.Sánchez@zmail.com')
 INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES( '680-548-8404',NULL,'Terri','Lee','Duffy','Terri.Duffy@zmail.com')
 INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES( '393-416-2902',NULL,'Roberto',NULL,'Tamburello','Roberto.Tamurello@zmail.com')
 INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES( '990-536-6948',NULL,'Rob',NULL,'Walters','Rob.Walters@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('439-393-5035','Ms.','Gail','A','Erickson','Gail.Erickson@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('499-105-5313','Mr.','Jossef','H','Goldberg','Jossef.Goldberg@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('253-558-2374',NULL,'Dylan','A','Miller','Dylan.Miller@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('567-905-2528',NULL,'Diane','L','Margheim','Diane.Margheim@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('725-995-3095',NULL,'Gigi','N','Matthew','Gigi.Matthew@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('967-989-6877',NULL,'Michael',NULL,'Raheem','Michael.Raheem@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('365-807-7956',NULL,'Ovidiu','V','Cracium','Ovidiu.Cracium@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('169-422-3059',NULL,'Thierry','B','DHers','Hers@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('363-197-9968','Ms.','Janice','M','Galvin','Janice.Galvin@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('352-696-1492',NULL,'Michael','I','Sullivan','Michael.Sullivan@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('216-438-5846',NULL,'Sharon','B','Salavaria','Sharon.Salavaria@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('484-441-7990',NULL,'David','M','Bradley','David.Bradley@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('865-219-1693',NULL,'Kevin','F','Brown','Kevin.Brown@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('678-586-3541',NULL,'John','L','Wood','John.Wood@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('705-806-6951',NULL,'Mary','A','Dempsey','Mary.Dempsey@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('742-478-8110',NULL,'Wanida','M','Benshoof','Wanida.Benshoof@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('648-837-1366',NULL,'Terry','J','Eminhizer','Terry.Eminhizer@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('874-343-3884',NULL,'Sariya','E','Harnpadoungsataya','Sariya.Harnpadoungsataya@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('509-366-2211',NULL,'Mary','E','Gibson','Mary.Gibson@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('821-986-5016','Ms.','Jill','A','Williams','Jill.Williams@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('934-321-7847',NULL,'James','R','Hamilton','James.Hamilton@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('318-943-4876',NULL,'Peter','J','Krebs','Peter.Krebs@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('494-639-6293',NULL,'Jo','A','Brown','Jo.Brown@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('831-417-2476',NULL,'Guy','R','Gilbert','Guy.Gilbert@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('633-744-8375',NULL,'Mark','K','McArthur','Mark.McArthur@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('753-222-2319',NULL,'Britta','L','Simon','Britta.Simon@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('767-710-6408',NULL,'Margie','W','Shoop','Margie.Shoop@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('860-174-2978',NULL,'Rebecca','A','Laszlo','Rebecca.Laszlo@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('448-438-7197',NULL,'Annik','O','Stahl','Annik.Stahl@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('934-331-4094',NULL,'Suchitra','O','Mohan','Suchitra.Mohan@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('559-269-4783',NULL,'Brandon','G','Heidepriem','Brandon.Heidepriem@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('518-304-8863',NULL,'Jose','R','Lugo','Jose.Lugo@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('691-733-9396',NULL,'Chris','O','Okelberry','Chris.Okelberry@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('135-545-5022',NULL,'Kim','B','Abercrombie','Kim.Abercrombie@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('950-680-5621',NULL,'Ed','R','Dudenhoefer','Ed.Dudenhoefer@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('945-848-5777',NULL,'JoLynn','M','Dobney','JoLynn.Dobney@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('972-319-8033',NULL,'Bryan',NULL,'Baker','Bryan.Baker@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('967-775-9237',NULL,'James','D','Kramer','James.Kramer@zmail.com')
INSERT dbo.Person (SSN, Title,FirstName,MiddleName,LastName,Email)
     VALUES('307-164-2466',NULL,'Nancy','A','Anderson','Nancy.Anderson@zmail.com')
